tasks:
  - name: 'qVim: Installing dependencies and running server to GitPod'
    command: pyenv install 3.10.4 && pyenv shell 3.10.4 && pip3 install -r requirements.txt && npm install && python3 main.py

ports:
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 5005
    visibility: public