tasks:
  - name: 'qVim: Installing dependencies to GitPod'
    init: echo "Installing dependencies to GitPod" && pyenv install 3.10.4 && pyenv shell 3.10.4 && pip3 install -r requirements.txt && npm install
    command: python3 main.py

ports:
  - port: 3000
    visibility: private
    onOpen: open-browser
  - port: 5005
    visibility: private